cloudnat_region  = "us-east1"
router_name = "cr-d-services-base-usea1-cr1"
bgp_asn = "64519"
ip_count = "2"
nat_name = "nat-d-services-base-usea1-nat1"
nat_ip_allocate_option = "MANUAL_ONLY"
source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
